name: 'Artifact Android local tests'
description: 'Runs Android local tests on the Dagger LOCAL-SNAPSHOT artifacts.'

runs:
  using: "composite"
  steps:
    - name: 'Check out repository'
      uses: actions/checkout@v4
    - name: 'Cache Gradle files'
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: 'Download local snapshot for tests'
      uses: actions/download-artifact@v4
      with:
        name: local-snapshot
        path: ~/.m2/repository/com/google/dagger
    - name: 'Install Java ${{ env.USE_JAVA_VERSION_FOR_GRADLE }}'
      uses: actions/setup-java@v4
      with:
        distribution: '${{ env.USE_JAVA_DISTRIBUTION }}'
        java-version: '${{ env.USE_JAVA_VERSION_FOR_GRADLE }}'
    - name: 'Gradle Android local tests (AGP ${{ env.USE_AGP_VERSION }})'
      run: ./util/run-local-gradle-android-tests.sh "${{ env.USE_AGP_VERSION }}"
      shell: bash
    - name: 'Upload test reports (AGP ${{ env.USE_AGP_VERSION }})'
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: tests-reports-agp-${{ env.USE_AGP_VERSION }}
        path: ${{ github.workspace }}/**/build/reports/tests/*
