name: 'Bazel build'
description: 'Builds all java/ sources with Bazel.'

runs:
  using: "composite"
  steps:
    - name: 'Install Java ${{ env.USE_JAVA_VERSION }}'
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.USE_JAVA_VERSION }}'
    - name: 'Cache Bazel files'
      uses: actions/cache@v2
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-bazel-build-
    - name: 'Java build'
      run: bazel build //java/...
      shell: bash
    - name: 'Clean bazel cache'
      # According to the documentation, we should be able to exclude these via
      # the actions/cache path, e.g. "!~/.cache/bazel/*/*/external/" but that
      # doesn't seem to work.
      run: |
        rm -rf $(bazel info repository_cache)
        rm -rf ~/.cache/bazel/*/*/external/
      shell: bash
