/*
 * Copyright (C) 2026 The Dagger Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dagger.internal.codegen;

import androidx.room3.compiler.processing.util.Source;
import com.google.common.collect.ImmutableCollection;
import com.google.common.collect.ImmutableList;
import dagger.testing.compile.CompilerTests;
import java.io.File;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

/**
 * Tests that using a {@code @Module} from a library that was not processed by Dagger yields a
 * clear error (https://github.com/google/dagger/issues/5146).
 */
@RunWith(Parameterized.class)
public class ModuleMissingFactoryErrorTest {
  @Parameters(name = "{0}")
  public static ImmutableCollection<Object[]> parameters() {
    return CompilerMode.TEST_PARAMETERS;
  }

  private final CompilerMode compilerMode;

  public ModuleMissingFactoryErrorTest(CompilerMode compilerMode) {
    this.compilerMode = compilerMode;
  }

  @Test
  public void moduleFromLibraryWithoutDaggerCompiler_reportsHelpfulError() {
    Source libraryModule =
        CompilerTests.javaSource(
            "lib.LibraryModule",
            "package lib;",
            "",
            "import dagger.Module;",
            "import dagger.Provides;",
            "",
            "@Module",
            "public final class LibraryModule {",
            "  @Provides",
            "  static String provideString() {",
            "    return \"hello\";",
            "  }",
            "}");

    // Compile the library without Dagger's annotation processor so no *Factory is generated.
    ImmutableList<File> libraryClasspath = CompilerTests.libraryCompiler(libraryModule).compile();

    Source component =
        CompilerTests.javaSource(
            "test.TestComponent",
            "package test;",
            "",
            "import dagger.Component;",
            "import lib.LibraryModule;",
            "",
            "@Component(modules = LibraryModule.class)",
            "interface TestComponent {",
            "  String string();",
            "}");

    CompilerTests.daggerCompiler(component)
        .withAdditionalClasspath(libraryClasspath)
        .withProcessingOptions(compilerMode.processorOptions())
        .compile(
            subject -> {
              subject.hasErrorContaining("LibraryModule_ProvideStringFactory is missing");
              subject.hasErrorContaining("Dagger compiler was not applied");
              subject.hasErrorContaining("lib.LibraryModule");
            });
  }

  @Test
  public void moduleFromLibraryWithOnlyBinds_doesNotRequireFactory() {
    Source libraryModule =
        CompilerTests.javaSource(
            "lib.LibraryBindsModule",
            "package lib;",
            "",
            "import dagger.Binds;",
            "import dagger.Module;",
            "import javax.inject.Inject;",
            "",
            "@Module",
            "public abstract class LibraryBindsModule {",
            "  @Binds",
            "  abstract Object bindObject(Foo foo);",
            "",
            "  public static final class Foo {",
            "    @Inject",
            "    Foo() {}",
            "  }",
            "}");

    ImmutableList<File> libraryClasspath = CompilerTests.libraryCompiler(libraryModule).compile();

    Source component =
        CompilerTests.javaSource(
            "test.TestComponent",
            "package test;",
            "",
            "import dagger.Component;",
            "import lib.LibraryBindsModule;",
            "",
            "@Component(modules = LibraryBindsModule.class)",
            "interface TestComponent {",
            "  Object object();",
            "}");

    // @Binds does not generate a module method factory; @Inject on Foo is generated by the
    // consuming compilation via InjectBindingRegistry.
    CompilerTests.daggerCompiler(component)
        .withAdditionalClasspath(libraryClasspath)
        .withProcessingOptions(compilerMode.processorOptions())
        .compile(subject -> subject.hasErrorCount(0));
  }
}
