name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  bazel-test:
    name: 'Bazel tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - uses: ./.github/actions/cache-local-maven
      - uses: ./.github/actions/cache-bazel
      - uses: ./.github/actions/cache-gradle
      - name: 'Run Bazel tests'
        run: bazel test --test_output=errors //...
        shell: bash
      - name: 'Install local snapshot'
        run: ./util/install-local-snapshot.sh
        shell: bash
      - name: 'Upload local snapshot for tests'
        uses: actions/upload-artifact@v2
        with:
          name: local-snapshot
          path: ~/.m2/repository/com/google/dagger
  artifact-java-local-tests:
    name: 'Artifact Java local tests'
    needs: bazel-test
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v2
    - uses: ./.github/actions/cache-gradle
    - uses: ./.github/actions/download-local-snapshots
    - name: 'Gradle Java local tests'
      run: ./util/run-local-gradle-tests.sh
      shell: bash
  artifact-android-local-tests:
    name: 'Artifact Android local tests (AGP ${{ matrix.agp }})'
    needs: bazel-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agp: ['4.1.0', '4.2.0-beta01']
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - uses: ./.github/actions/cache-gradle
      - uses: ./.github/actions/download-local-snapshots
      - name: 'Gradle Android local tests (AGP ${{ matrix.agp }})'
        run: ./util/run-local-gradle-android-tests.sh "${{ matrix.agp }}"
        shell: bash
  publish-snapshot:
    name: 'Publish snapshot'
    needs: [bazel-test, artifact-java-local-tests, artifact-android-local-tests]
    if: github.event_name == 'push' && github.repository == 'google/dagger' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - uses: ./.github/actions/cache-local-maven
      - uses: ./.github/actions/cache-bazel
      - uses: ./.github/actions/cache-gradle
      - name: 'Publish latest docs'
        run: ./util/generate-latest-docs.sh
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: 'Publish latest snapshot'
        run: ./util/publish-snapshot-on-commit.sh
        shell: bash
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
